title: Бот для проведения опросов через Telegram
email: aleks.lobzov@gmail.com
description: Это описание моего Pet-проекта по проведению опросов через Telegram
baseurl: "/SurveyDemoBot"
url: "https://alobzov.github.io"
github_username: alobzov
markdown: kramdown
author:
  name: "Алексей Лобзов"
  email: aleks.lobzov@gmail.com
encoding: utf-8
timezone: Europe/Moscow
exclude:
  - README.md